brew "direnv"
cask "1password"
cask "karabiner-elements"
cask "aqua-voice"
cask "blackhole-2ch"
cask "claude"
cask "codex"
cask "codex-app"
cask "docker-desktop"
cask "ghostty"
cask "google-chrome"
# cask "orbstack" # Docker SandboxとDocker MCP Toolkitに未対応(2026-08時点、orbstack/orbstack issue #2295, #2175, #2056)。対応されたら再検討する
cask "superset"
